### PR TITLE
Lumen 6

### PR DESCRIPTION
**Pull request by neclimdul**
Changes proposed in this pull request:

 *  Update composer.json to support lumen 6.x
 * Update tests to use prophecy

### CODE REVIEW

**Comment by neclimdul** [comment]
I don't know if the prophecy changes where strictly necessary but I couldn't run the test suite after updating the composer requirements with lumen 6 because the mock generator was broken. Its abandoned anyways.

**Review by Jalle19 — APPROVED** [review]

**Review by hugovk — DISMISSED** [review]
Please could you update it so the CI still passes?

```
PHP Fatal error:  Declaration of SebastianBergmann\Comparator\DOMNodeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in /home/travis/build/digiaonline/lumen-chained-exception-handler/vendor/sebastian/comparator/src/DOMNodeComparator.php on line 110
```

https://travis-ci.org/digiaonline/lumen-chained-exception-handler/builds/619936420

**Comment by Jalle19** [comment]
I'd probably change the tests to use `getMockBuilder(Foo::class)` instead of introducing a new dependency.

**Comment by neclimdul** [comment]
I'm really confused about how your CI is working, this is pretty frustrating because this was supposed to be a trivial changes :angry:

Prophecy isn't actually a new dependency, its been bundled with phpunit for a long time but it seemed like Travis didn't install because it claimed the class didn't exist. I added it to composer.json to see if it "fixed" it which it sort of did. You can see in the lock file that non _real_ changes where made.

I actually didn't change any tests changed how the assertions where made so there wasn't anything to change to getMockBuilder(). The failure was that the mockBuilder fatal'd in its eval() step trying to create the ExceptionHandler. It didn't seem worth trying to fix so I converted to a simpler system that _should_ have been trivial.

The current failure is a bug 100% inside phpunit unfortunately. I'm not clear on why this is triggering it yet, I'll try to find some time to figure this out though or roll back to the mocks or... i don't know.

**Comment by neclimdul** [comment]
bah, travis is passing now without changing the tests. I don't get it but if its happy that's the easiest fix. Sorry about the noisy PR.

**Comment by Jalle19** [comment]
Closing this in favor of https://github.com/digiaonline/lumen-chained-exception-handler/pull/5

**Pull request closed without merging**
