### PR TITLE
Drop composer.lock, support Lumen 6.x

### PR DESCRIPTION
**Pull request by Jalle19**
Replaces https://github.com/digiaonline/lumen-chained-exception-handler/pull/4

### CODE REVIEW

**Comment by Jalle19** [comment]
Had to drop the last commit (test on PHP 7.4) since there is no version of phpunit that works on both 5.6 and 7.4.

**Comment by hugovk** [comment]
What's the schedule for dropping PHP 5.6? It's EOL since 31 Dec 2018.

* https://www.php.net/supported-versions.php

**Comment by Jalle19** [comment]
I guess we could, but then we'd have to bump the major version which I think we should avoid. After all we don't really use any fancy language features so any minimum required version bump would only be arbitrary.

**Comment by hugovk** [comment]
OK!

In a way it's more important to test 7.4 than 5.6, but if 7.3 works, 7.4 probably works too.

**Review by hugovk — APPROVED** [review]

**Comment by Jalle19** [comment]
Yeah that's true. We can probably drop 5.6 in the beginning of next year.

**Comment by Jalle19** [comment]
https://packagist.org/packages/nordsoftware/lumen-chained-exception-handler#1.0.3

**Pull request merged**
