### PR TITLE
Support Lumen 7.x

### PR DESCRIPTION
**Pull request by Jalle19**
Replaces #7

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks!

Also need to drop 5.6 - 7.1 in Travis CI:

https://github.com/digiaonline/lumen-chained-exception-handler/blob/d9843601918a1b08a2472a1b9621382cb4c2975a/.travis.yml#L3-L8

Could add 7.4 there too.

**Comment by Jalle19** [comment]
@hugovk done

**Comment by hugovk** [comment]
Thank you!

**Comment by hugovk** [comment]
Feel free to release this (and the other lumen projects) whenever you like! You should still have access.

**Comment by Jalle19** [comment]
I'll try to remember

**Pull request merged**
