### PR TITLE
Update composer.json to support PHP8

### LINKED ISSUE #31: Support for PHP 8
### What did you do?

Tried to install on `php:8.0-fpm-alpine`

### What did you expect to happen?

Successful install

### What actually happened?

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nordsoftware/lumen-newrelic[3.0.0, ..., 3.1.1] require php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.
    - Root composer.json requires nordsoftware/lumen-newrelic ^3.0 -> satisfiable by nordsoftware/lumen-newrelic[3.0.0, 3.1.0, 3.1.1].
```

### What versions of relevant language, framework and this module are you using?

Here's the basic `composer.json` I'm using.

```json
{
    "name": "laravel/lumen",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^8.0",
        "laravel/lumen-framework": "^8.0",
        "nordsoftware/lumen-newrelic": "^3.0",
        "zircote/swagger-php": "^3.0"
    },
    "require-dev": {
        "fzaninotto/faker": "^1.9.1",
        "phpunit/phpunit": "^9.3",
        "mockery/mockery": "^1.3.1"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

PHP 8 doesn't bring anything that would break the current version of the package, the upgrade should be straight forward, something like

```json
"require": {
        "php": "^7.2 | ^8.0",
        "intouch/newrelic": "^1.0",
        "illuminate/support": "^5.5 | ^6.0 | ^7.0 | ^8.0",
        "nordsoftware/lumen-chained-exception-handler": "^2.0"
    },
```

May also require an upgrade of the `nordsoftware/lumen-chained-exception-handler` package.

### PR DESCRIPTION
**Pull request by ls-renaud-tilte**
Fixes https://github.com/digiaonline/lumen-newrelic/issues/31

Changes proposed in this pull request:

 * Update composer.json to support PHP8
 * Also update PHPUnit to latest version for same reason.
 * Update travis workflow to test PHP8

Note: I also suggest you switch from Travis to GitHub workflows for this repo. This is out of scope for this repo, I'll let the owner decide on this part.

### CODE REVIEW

**Comment by hugovk** [comment]
Big +1 for replacing Travis CI with GitHub Actions, thanks!

Please could you also replace the Travis badge in the README? Something like:

```md
[![GitHub Actions status](https://github.com/digiaonline/lumen-chained-exception-handler/workflows/Test/badge.svg)](https://github.com/digiaonline/lumen-chained-exception-handler/actions)
```

**Comment by ls-renaud-tilte** [comment]
> Big +1 for replacing Travis CI with GitHub Actions, thanks!
> 
> Please could you also replace the Travis badge in the README? Something like:
> 
> ```lisp
> [GitHub Actions status](https://github.com/digiaonline/lumen-chained-exception-handler/actions)
> ```

Excellent idea. This has been done, but the build is not running yet, one of the admins will have to enable Github actions for the repo before it can actually pull the badge.

Also, the latest version of PHPUnit that supports PHP 7.2 is PHPUnit 8.5, which is not able to run code coverage (https://github.com/sebastianbergmann/phpunit/issues/4533#issuecomment-735755816).

I think it's better to drop the support for PHP 7.2 for this package too (7.2 is end of life anyway, it's safer for people to migrate to at least PHP 7.3) and use all the latest libraries for this repo (PHPUnit, php-coveralls) rather than sticking with all versions of PHP.

Of course, creating a new tag once the PR is merged will let the choice to the end user, knowing that people who require the extension for their PHP8 app will most likely not need PHP7.2, and devs who require the 7.2 don't care about support for PHP 8.

**Comment by hugovk** [comment]
> Excellent idea. This has been done, but the build is not running yet, one of the admins will have to enable Github actions for the repo before it can actually pull the badge.

I'm an admin, I don't think there's anything to do activate GHA, we just need to merge in a workflow file. It's passing on your branch:

* https://github.com/ls-renaud-tilte/lumen-chained-exception-handler/actions/runs/531174214

And coverage is good:

* https://coveralls.io/github/ls-renaud-tilte/lumen-chained-exception-handler

PHP versions:

I'm generally of the opinion we only need to support the [upstream PHP versions](https://www.php.net/supported-versions.php) (currently 7.3+), at a minimum, and we can especially drop EOL versions that cause problems, such as the coverage thing you mention here.

@Jalle19 Thoughts on dropping PHP 7.2?

**Comment by ls-renaud-tilte** [comment]
PR is now ready for review / merge. It's really up to you to accept it or change it regarding the PHP version you want to support.

This PR is also required for the `laravel-lumen` PR, though that one is not a high priority since the NewRelic PHP agent isn't ready for PHP 8.

**Review by hugovk — APPROVED** [review]

**Comment by hugovk** [comment]
Thank you! This has now been released as version 3.0.0:

https://packagist.org/packages/nordsoftware/lumen-chained-exception-handler#3.0.0

**Pull request merged**
